@startuml Holocron
skinparam theme materia

start
:Iniciar Monitor de Compromissos;

while (Sistema Ativo?) is (sim)
  :Abrir arquivo de compromissos;

  partition "Relatório Diário" {
    if (É 08:00 AM?) then (sim)
      if (Enviado hoje?) then (não)
        :Gerar e Enviar Agenda (Telegram);
        :Marcar como enviado;
      endif
    endif
  }

  partition "Alerta de 1 Hora" {
    :Ler próxima linha do arquivo;
    if (Falta 1h para o compromisso?) then (sim)
      if (Já notificado?) then (não)
        :Enviar Alerta;
      endif
    endif
  }

  :Aguardar 5 min;
endwhile (não)

stop
@endum